[build]
target = "thumbv6m-none-eabi"      

[target.thumbv6m-none-eabi]
runner = "probe-rs run --chip STM32G030F6"
rustflags = [
  "-C", "linker=arm-none-eabi-ld",
  "-C", "link-arg=-Tdefmt.x",
  "-C", "link-arg=-Tlink.x"
]

[profile.dev]
opt-level = 1

[profile.release]
opt-level = "z"        # Optimize for the smallest code size (can also use "s" for size with some speed consideration)
lto = true             # Enable Link Time Optimization (LTO) for whole-program optimization
codegen-units = 1      # Reduce code generation units for more aggressive optimization (at the cost of slower compilation)
panic = "abort"        # Use 'abort' instead of 'unwind' for panic handling, eliminating unwinding code
# debug = true
strip = "debuginfo"    # Remove debug information from the binary


[env]
DEFMT_LOG = "debug"